# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
  # - windows
julia:
  - 1.0
  - 1.2
  - nightly
branches: # build master branch + PRs
  only:
  - master
matrix:
  # fast_finish marks the build as passing even if allow_failures builds are still running
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: windows
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                              Pkg.build("SDPAFamily");
                                              Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
